height = input float('Insira sua altura (exemplo - 1,70): ').replace(',', '.')
weight = input float("Insira seu peso (exemplo - 75,3): ").replace(',', '.')
height = float(height)
weight = float(weight)
imc = weight/(height * height)
print(f'Seu imc é : {imc:.2f}')
